# Generated by Django 6.0.5 on 2026-05-19 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('storage_key', models.CharField(max_length=510, unique=True)),
                ('downloads', models.IntegerField(default=0)),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reports', models.ManyToManyField(db_table='report_attachments', related_name='documents', to='reports.report')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['shared'], name='documents_shared_cae11b_idx'), models.Index(fields=['uploaded_by'], name='documents_uploade_aad805_idx')],
            },
        ),
    ]
