# Generated by Django 6.0.5 on 2026-06-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='Others', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
