# Generated by Django 6.0.5 on 2026-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('national_manager', 'National Manager'), ('regional_coordinator', 'Regional Coordinator'), ('field_officer', 'Field Officer')], default='regional_coordinator', max_length=50),
        ),
    ]
