# Generated by Django 6.0.5 on 2026-05-19 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('answered', 'Answered'), ('archived', 'Archived')], default='active', max_length=50)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('regional', 'Regional'), ('anonymous', 'Anonymous')], default='public', max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('commitments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prayer_requests',
            },
        ),
        migrations.CreateModel(
            name='PrayerCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='prayer.prayerrequest')),
            ],
            options={
                'db_table': 'prayer_commitments',
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['status'], name='prayer_requ_status_0bfee3_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['visibility', 'region'], name='prayer_requ_visibil_faeba1_idx'),
        ),
        migrations.AddIndex(
            model_name='prayercommitment',
            index=models.Index(fields=['request'], name='prayer_comm_request_017d67_idx'),
        ),
        migrations.AddIndex(
            model_name='prayercommitment',
            index=models.Index(fields=['user'], name='prayer_comm_user_id_079851_idx'),
        ),
    ]
