# Generated by Django 6.0.5 on 2026-05-19 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Financial', 'Financial'), ('Equipment', 'Equipment'), ('Spiritual', 'Spiritual'), ('Technical', 'Technical'), ('Training', 'Training')], max_length=100)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under Review'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='submitted', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_requests',
            },
        ),
        migrations.CreateModel(
            name='SupportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportrequest')),
            ],
            options={
                'db_table': 'support_comments',
            },
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['region', 'status'], name='support_req_region_04cd35_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['requester'], name='support_req_request_1a383a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['assigned_to'], name='support_req_assigne_5b0d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcomment',
            index=models.Index(fields=['request'], name='support_com_request_fd806c_idx'),
        ),
    ]
