# Generated by Django 6.0.5 on 2026-06-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportrequest_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='ai_priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='AI-assigned priority based on content analysis', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='ai_priority_confidence',
            field=models.IntegerField(blank=True, help_text='Confidence score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='ai_priority_reason',
            field=models.TextField(blank=True, help_text='Why AI assigned this priority', null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='manual_priority_override',
            field=models.BooleanField(default=False),
        ),
    ]
