# Generated by Django 6.0.5 on 2026-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportrequest_ai_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('submitted_to_coordinator', 'Submitted to Coordinator'), ('submitted_to_manager', 'Submitted to Manager'), ('under review', 'Under Review'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed'), ('returned_by_coordinator', 'Returned by Coordinator'), ('returned_by_manager', 'Returned by Manager')], default='submitted', max_length=50),
        ),
    ]
