import json
import urllib.parse
from channels.generic.websocket import AsyncJsonWebsocketConsumer
from django.contrib.auth import get_user_model
from rest_framework_simplejwt.tokens import AccessToken
from channels.db import database_sync_to_async

User = get_user_model()

@database_sync_to_async
def get_user_from_token(token_string):
    try:
        access_token = AccessToken(token_string)
        user_id = access_token['user_id']
        return User.objects.get(id=user_id)
    except Exception:
        return None


class NotificationConsumer(AsyncJsonWebsocketConsumer):
    """
    Consumer handling real-time push notifications for authenticated users.
    """
    async def connect(self):
        query_string = self.scope.get('query_string', b'').decode()
        query_params = urllib.parse.parse_qs(query_string)
        token = query_params.get('token', [None])[0]
        
        self.user = None
        if token:
            self.user = await get_user_from_token(token)
            
        if self.user:
            self.group_name = f"user_{self.user.id}_notifications"
            await self.channel_layer.group_add(
                self.group_name,
                self.channel_name
            )
            await self.accept()
        else:
            await self.close()

    async def disconnect(self, close_code):
        if hasattr(self, 'group_name'):
            await self.channel_layer.group_discard(
                self.group_name,
                self.channel_name
            )

    async def receive_json(self, content):
        action = content.get('action')
        notification_id = content.get('notification_id')
        if action == 'mark_read' and notification_id:
            success = await self.mark_notification_read(notification_id)
            await self.send_json({"success": success, "notification_id": notification_id})

    @database_sync_to_async
    def mark_notification_read(self, notification_id):
        from apps.notifications.models import Notification
        try:
            notification = Notification.objects.get(id=notification_id, user=self.user)
            notification.read = True
            notification.save()
            return True
        except Notification.DoesNotExist:
            return False

    async def new_notification(self, event):
        """
        Handler to transmit message to the WebSocket client when an event is received from channel group.
        """
        await self.send_json(event['data'])


class AIProgressConsumer(AsyncJsonWebsocketConsumer):
    """
    Streams AI classification progress for a specific report.
    """
    async def connect(self):
        self.report_id = self.scope['url_route']['kwargs']['report_id']
        self.group_name = f"ai_progress_{self.report_id}"
        
        await self.channel_layer.group_add(
            self.group_name,
            self.channel_name
        )
        await self.accept()

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard(
            self.group_name,
            self.channel_name
        )

    async def progress_update(self, event):
        """
        Handles progress messages generated by the celery background task.
        """
        await self.send_json(event['data'])


class SessionConsumer(AsyncJsonWebsocketConsumer):
    """
    Listens for administrative session termination commands.
    """
    async def connect(self):
        query_string = self.scope.get('query_string', b'').decode()
        query_params = urllib.parse.parse_qs(query_string)
        token = query_params.get('token', [None])[0]
        
        self.user = None
        if token:
            self.user = await get_user_from_token(token)
            
        if self.user:
            self.group_name = f"user_{self.user.id}_sessions"
            await self.channel_layer.group_add(
                self.group_name,
                self.channel_name
            )
            await self.accept()
        else:
            await self.close()

    async def disconnect(self, close_code):
        if hasattr(self, 'group_name'):
            await self.channel_layer.group_discard(
                self.group_name,
                self.channel_name
            )

    async def session_terminated(self, event):
        """
        Force-logs the user out on active session termination.
        """
        await self.send_json({
            "type": "session_terminated",
            "message": "Your session has been terminated by an administrator."
        })
