# Generated by Django 6.0.5 on 2026-05-19 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Outreach', 'Outreach'), ('Bible Study', 'Bible Study'), ('Training', 'Training'), ('Meeting', 'Meeting'), ('Community Event', 'Community Event'), ('Prayer Meeting', 'Prayer Meeting'), ('Youth Program', 'Youth Program')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField(db_column='activity_date')),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned')], default='draft', max_length=50)),
                ('participants', models.IntegerField(default=0)),
                ('demographics', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('outcomes', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('prayer_requests', models.TextField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('overridden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['region', 'status'], name='reports_region_412e47_idx'), models.Index(fields=['date'], name='reports_activit_fab863_idx'), models.Index(fields=['submitted_by'], name='reports_submitt_a8be07_idx')],
            },
        ),
    ]
