# Generated by Django 6.0.5 on 2026-05-20 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
