# Generated by Django 6.0.5 on 2026-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_approved_at_report_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
