# Generated by Django 6.0.5 on 2026-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('submitted_to_coordinator', 'Submitted to Coordinator'), ('submitted_to_manager', 'Submitted to Manager'), ('approved', 'Approved'), ('returned', 'Returned'), ('returned_by_coordinator', 'Returned by Coordinator'), ('returned_by_manager', 'Returned by Manager')], default='draft', max_length=50),
        ),
    ]
